[package]
name = "key_bnc"
version = "1.3.0"
authors = ["dougalg <dougalg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
counter = "0.4.3"
tokenizers = "0.10.1"
